### ISSUE TITLE
Plugin installing is flakey

### ISSUE THREAD

**Issue by timja** [jenkinsci/acceptance-test-harness#1284] opened 2023-07-19 07:20 UTC
> Closing, the DeployPluginTest issues are preexisting.

This new functionality is flakey unfortunately, e.g. lots failed here:
https://ci.jenkins.io/blue/organizations/jenkins/Core%2Facceptance-test-harness/detail/PR-1261/6/tests

cc @janfaracik / @NotMyFault

https://ci.jenkins.io/blue/organizations/jenkins/Core%2Facceptance-test-harness/detail/PR-1261/11/tests/

_Originally posted by @timja in https://github.com/jenkinsci/acceptance-test-harness/issues/1274#issuecomment-1633255401_

**Comment by jtnord** [comment] 2023-07-21 10:14
I have seen [this failure](https://ci.jenkins.io/blue/organizations/jenkins/Core%2Facceptance-test-harness/detail/PR-1282/3/tests/) with the weekly release ( `2.414` )

there doesn't seem to be anything in the ATH that would cause this flakyness - so does this mean that core has regressed - returning from the installing page too early?

Looking at the recording - this looks like a [regression in core](https://ci.jenkins.io/job/Core/job/acceptance-test-harness/job/PR-1282/3/testReport/junit/plugins/MatrixAuthPluginTest/latest_linux_jdk17_firefox_split8___helloWorld/attachments/ui-recording.mov) to me.

**Comment by jtnord** [comment] 2023-07-21 10:54
https://github.com/jenkinsci/acceptance-test-harness/pull/1289 related - but I do not believe this is the cause of the issue.

**Comment by timja** [comment] 2023-07-21 10:57
Possibly, it would be this:
https://github.com/jenkinsci/jenkins/pull/8025

I wasn't able to reproduce locally in Chrome.

**Comment by jtnord** [comment] 2023-07-21 11:09
it's like the "install" option sends an empty form to Jenkins (at least Jenkins does not attempt to even start to download / install anything).
#1165 would at least help here.

**Comment by jtnord** [comment] 2023-07-21 13:05
easy enough to reproduce locally..  with `docker run --shm-size=256m -d -p 127.0.0.1:4444:4444 -p 127.0.0.1:5900:5900 -e no_proxy=localhost -e SCREEN_WIDTH=1680 -e SCREEN_HEIGHT=1090 selenium/standalone-firefox:4.6.0`   , `REMOTE_WEBDRIVER_URL=http://127.0.0.1:4444/wd/hub` and ` mvn test -Dtest=MatrixAuthPluginTest`

The HAR looks like there is no POST to install.

<img width="480" alt="image" src="https://github.com/jenkinsci/acceptance-test-harness/assets/494726/43fb2977-a0f6-4b62-b0f3-a09e7b84de0a">

**Comment by jtnord** [comment] 2023-07-21 13:12
looking at the screen recording again in slow motion - it looks like the install button becomes disabled after the matrix-auth plugin is checked - which may tie in with the fact that there is no call to `install`
strangely the button starts enabled though - which I think is a bug.  the button should start disabled as this is the sate until the page has been acted upon.

anyway - as the click on the checkbox causes javascript to run (which changes the state of the button) we probably should sleep until the button has been enabled.

**Comment by jtnord** [comment] 2023-07-21 14:52
with the following patch I am 50% correct in my deduction...

```patch
diff --git a/src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayerImpl.java b/src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayerImpl.java
index a60dc24d..728e096f 100644
--- a/src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayerImpl.java
+++ b/src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayerImpl.java
@@ -95,6 +95,7 @@ public class CapybaraPortingLayerImpl implements CapybaraPortingLayer {
     @Override
     public void clickButton(String text) {
         WebElement e = find(by.button(text));
+        assert e.isEnabled() : "Attempted to click a button ("+text+") but that button is disabled";
         e.click();
     }
```

produces

```
[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   MatrixAuthPluginTest>CapybaraPortingLayerImpl.clickButton:98 Attempted to click a button (Install) but that button is disabled
[ERROR] Errors:
[ERROR]   MatrixAuthPluginTest.helloWorld � IllegalArgument matrix-auth plugin not installed
[INFO]
[ERROR] Tests run: 2, Failures: 1, Errors: 1, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:29 min
[INFO] Finished at: 2023-07-21T15:46:59+01:00
[INFO] ------------------------------------------------------------------------
```

So it would appear that sometimes the button is enabled which means installing plugins would be a no-op, and other times the button is enabled - but it did not do what it said on the tin... 😱   

looking again at the screen recording the button starts as enabed and then gets set to disabled - this is IMO a bug in Jenkins, esp as the button can not be enabled until something has been checked - which can not happen until after the page has loaded and something has been clicked.

so that is one part - clicking on a non enabled button - the javascript is going to be asyn at any rate so we should wait for the button to be enabled before we click it...

but the second - that the install button is clicked and does nothing... that is interesting also.

**Comment by jtnord** [comment] 2023-07-21 17:37
defiantly a production bug @janfaracik

made the ath wait until "install" is enabled before clicking install, and wating until it is stale before attempting to move on (so as not to loose any javascript that may not yet have submitted the form) and the test failed and it was waiting for the button to be enabled until the timeout.

<img width="838" alt="image" src="https://github.com/jenkinsci/acceptance-test-harness/assets/494726/e65bfd1d-826f-496f-a51c-63105bcd5535">

**Comment by jtnord** [comment] 2023-07-21 19:54
allthough the tests pass with remote-webdriver-chrome looking at the browser as it is being drivven shows a strange interaction with the page, there is a long pause between searching for matrix-auth and it being selected for install - possibly this is enough to allow the initial javascript to disable the button to not conflict with the click handler javascript.

**Comment by basil** [comment] 2023-07-21 23:03
I was able to definitively implicate https://github.com/jenkinsci/jenkins/pull/8025 by widening the race window:

```javascript
diff --git a/core/src/main/resources/hudson/PluginManager/_table.js b/core/src/main/resources/hudson/PluginManager/_table.js
index dcc8a6840d..dbc06561d1 100644
--- a/core/src/main/resources/hudson/PluginManager/_table.js
+++ b/core/src/main/resources/hudson/PluginManager/_table.js
@@ -497,7 +497,7 @@ window.addEventListener("load", function () {
     checkbox.addEventListener("click", () => {
       setTimeout(() => {
         updateButton.disabled = !anyCheckboxesSelected();
-      });
+      }, 3000);
     });
   });
 
diff --git a/war/src/main/js/plugin-manager-ui.js b/war/src/main/js/plugin-manager-ui.js
index 95a95e7bc4..ceef43be41 100644
--- a/war/src/main/js/plugin-manager-ui.js
+++ b/war/src/main/js/plugin-manager-ui.js
@@ -100,7 +100,7 @@ function updateInstallButtonState() {
       setTimeout(() => {
         installButton.disabled = !anyCheckboxesSelected();
         installAfterRestartButton.disabled = !anyCheckboxesSelected();
-      });
+      }, 3000);
     });
   });
 }
```

With this patch to core, I can consistently reproduce the failure in `MatrixAuthPluginTest#helloWorld`.

**Comment by basil** [comment] 2023-07-21 23:17
I _possibly_ have chased away the test failure by removing the asynchrony from the original change? At least it's been running in a loop for 15 minutes and I haven't seen the test failure yet…

```javascript
diff --git a/core/src/main/resources/hudson/PluginManager/_table.js b/core/src/main/resources/hudson/PluginManager/_table.js
index dcc8a6840d..47d13bfc54 100644
--- a/core/src/main/resources/hudson/PluginManager/_table.js
+++ b/core/src/main/resources/hudson/PluginManager/_table.js
@@ -495,9 +495,7 @@ window.addEventListener("load", function () {
   );
   checkboxes.forEach((checkbox) => {
     checkbox.addEventListener("click", () => {
-      setTimeout(() => {
-        updateButton.disabled = !anyCheckboxesSelected();
-      });
+      updateButton.disabled = !anyCheckboxesSelected();
     });
   });
 
diff --git a/war/src/main/js/plugin-manager-ui.js b/war/src/main/js/plugin-manager-ui.js
index 95a95e7bc4..76b4aef103 100644
--- a/war/src/main/js/plugin-manager-ui.js
+++ b/war/src/main/js/plugin-manager-ui.js
@@ -97,10 +97,8 @@ function updateInstallButtonState() {
   const checkboxes = document.querySelectorAll("input[type='checkbox']");
   checkboxes.forEach((checkbox) => {
     checkbox.addEventListener("click", () => {
-      setTimeout(() => {
-        installButton.disabled = !anyCheckboxesSelected();
-        installAfterRestartButton.disabled = !anyCheckboxesSelected();
-      });
+      installButton.disabled = !anyCheckboxesSelected();
+      installAfterRestartButton.disabled = !anyCheckboxesSelected();
     });
   });
 }
```

**Comment by basil** [comment] 2023-07-21 23:29
> At least it's been running in a loop for 15 minutes and I haven't seen the test failure yet…

Removing the asynchrony did eventually fail after running the test locally in a loop for 25 minutes (about a dozen iterations), so that is _not_ the solution. But at least I have contributed something by demonstrating how to reproduce the failure within 1 iteration using the sleeps.

**Comment by basil** [comment] 2023-07-21 23:35
If anyone thinks they have come up with a solution to this bug, send me the patch and I will run it on my system in a loop for 30-60 minutes to see if the test failure rears its ugly head again…

**Comment by timja** [comment] 2023-07-22 20:40
@basil can you check https://github.com/jenkinsci/jenkins/pull/8293

**Comment by basil** [comment] 2023-07-22 23:38
I ran it for a loop for about 2 hours without any failures. :+1:

**Comment by basil** [comment] 2023-08-06 18:57
Fixed in https://github.com/jenkinsci/jenkins/pull/8293.

**Closed by basil** 2023-08-06 18:57 UTC
